MessageBoard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('board.urls')),
    path('superadmin/', admin.site.urls),
]

board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.manager_login, name="login"),
    path('logout/', views.manager_logout, name='logout'),
    path('manage_the_message/', views.manage, name='manage'),
    path('index/<int:page_num>/', views.index, name='index'),
    path('manage_the_message/<int:page_num>/', views.manage, name='manage'),
    path('write_message/', views.write_message, name='write_message'),
    path('check_pass/<int:message_id>/<int:page_num>/', views.check_pass, name='check_pass'),
    path('detail/<int:message_id>/<int:page_num>/', views.detail, name='detail'),
    path('', views.index, name="index")
]

board/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    def __str__(self):
        suffix = ''
        if len(self.message_text) > 30:
            suffix = '...'
        return '(' + str(self.send_time.date()) + ')' + self.message_text[:30] + suffix

    message_text = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)
    wechat_id = models.CharField(max_length=64)
    response_text = models.TextField(null=True, blank=True)
    is_checked = models.BooleanField(default=False)

board/views.py
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404

from .models import Message


def index(request, page_num=1):
    total_pages = int((Message.objects.filter(is_checked=True).count() - 1) / 10 + 1)
    if page_num >= 99999:
        page_num = total_pages
    start = (page_num - 1) * 10
    latest_message_list = Message.objects.filter(is_checked=True).order_by('-send_time')[start:start + 10]
    if page_num == 1:
        last_page = 1
    else:
        last_page = page_num - 1
    if page_num == total_pages:
        next_page = page_num
    else:
        next_page = page_num + 1
    context = {
        'latest_message_list': latest_message_list,
        'next_page': next_page,
        'last_page': last_page,
        'current_page': page_num,
        'total_pages': total_pages
    }
    return render(request, 'board/index.html', context)


@login_required
def manage(request, page_num=1):
    start = (page_num - 1) * 10
    need_to_check_list = Message.objects.order_by('-send_time')[start:start + 10]
    total_pages = int((Message.objects.count() - 1) / 10 + 1)
    if page_num == 1:
        last_page = 1
    else:
        last_page = page_num - 1
    if page_num == total_pages:
        next_page = page_num
    else:
        next_page = page_num + 1
    context = {
        'need_to_check_list': need_to_check_list,
        'next_page': next_page,
        'last_page': last_page,
        'current_page': page_num,
        'total_pages': total_pages
    }
    return render(request, 'board/manage.html', context)


def write_message(request):
    if request.method == 'POST':
        new_message = Message()
        new_message.message_text = request.POST['text-box']
        new_message.wechat_id = request.POST['wechat-box']
        new_message.save()
        return HttpResponseRedirect(reverse('board:index'))
    else:
        return render(request, 'board/write_message.html')


@login_required
def check_pass(request, message_id, page_num=1):
    message = get_object_or_404(Message, id=message_id)
    message.is_checked = True
    message.save()
    return HttpResponseRedirect(reverse('board:manage'), (page_num,))


@login_required
def detail(request, message_id, page_num=1):
    message = get_object_or_404(Message, id=message_id)
    if request.method == 'POST':
        message.response_text = request.POST['text-box']
        message.save()
        return HttpResponseRedirect(reverse('board:manage'), (page_num,))
    else:
        context = {
            'message': message,
            'current_page': page_num,
        }
        return render(request, 'board/detail.html', context)


def manager_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('board:manage'))
        else:
            return Http404()
    else:
        return render(request, 'board/login.html')


@login_required
def manager_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('board:index'))

board/templates/board/base.html
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Easy留言板</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'board/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet/less" href="{% static 'board/css/customStyle.less' %}">

</head>
<body>
<div class="container">
    {% block navbar %}
        <nav class="navbar navbar-expand navbar-dark bg-light">
            <a class="navbar-brand" href="">
                <img src="{% static 'board/assets/top.png' %}" alt="Logo">
            </a>
            <div class="navbar-text text-dark text-center lead"
                 style="margin: 0 auto;font-size: 30px;font-weight: bold;">留言板
            </div>

            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link text-info lead text-center" style="width: 85px;" href="{% url 'board:manage' %}">管理</a>
                </li>
            </ul>
        </nav>
    {% endblock %}
    {% block mainbody %}
        <p>Please overwrite this block!</p>
    {% endblock %}
</div>
<footer class="border-top bg-light">
    <div class="container text-center ">
        <!-- <img class="center-block" src="{% static 'board/assets/footer.jpeg' %}" width="50%" alt="Footer_logo"> -->
        Easy 留言板
    </div>
    <div class="text-center" style="margin: 30;">© 2019 Copyright: 白羽焰</div>
</footer>
<script src="{% static 'board/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'board/js/bootstrap.min.js' %}"></script>
<script src="{% static 'board/js/less.min.js' %}"></script>
</body>

</html>

board/templates/board/detail.html
{% extends "board/base.html" %}
{% load static %}

{% block navbar %}
    <nav class="navbar navbar-expand navbar-dark bg-light">
        <a class="navbar-brand" href="">
            <img src="{% static 'board/assets/top.png' %}" alt="Logo">
        </a>
        <div class="navbar-text text-dark text-center lead" style="margin: 0 auto;font-size: 30px;font-weight: bold;">留言板
        </div>

        <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link text-info lead text-center" style="width: 85px;"
                   href="{% url 'board:logout' %}">注销</a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block mainbody %}
    <div class="text-center" style="margin-top:50px;">
        <h1>留言详情</h1>
        <div class="jumbotron">
            <h3 class="display-3">{{ message.wechat_id }}</h3>
            <p class="lead">"{{ message.message_text }}"</p>
            <hr class="my-4">
            <form action="{% url 'board:detail' message.id 1 %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="text-box">回复</label>
                    <textarea required name="text-box" class="form-control" id="text-box" rows="3"></textarea>
                </div>
                <br>
                <input type="submit" class="btn btn-primary" value="提交">
            </form>
            <a class="btn btn-primary" href="{% url 'board:manage' %}">返回</a>
        </div>
    </div>


{% endblock %}

board/templates/board/index.html
{% extends "board/base.html" %}
{% load static %}

{% block mainbody %}
    <div class="text-center" style="margin-top:50px; margin-bottom: 50px;">
        {% if latest_message_list %}
            {% for message in latest_message_list %}
                <div class="card mb-3 border-primary">
                    <h4 class="card-header">{{ message.wechat_id }}</h4>
                    <div class="card-body">
                        <h5 class="card-title">{{ message.message_text }}</h5>
                        <h6 class="card-subtitle text-muted">{{ message.send_time|date:"Y年n月j日" }}</h6>
                    </div>
                    {% if message.response_text %}
                        <div class="card-footer bg-light">
                            <span class="text-info">编辑回复:</span>
                            {{ message.response_text }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            <p>There is no message on the board!</p>
        {% endif %}
        <div class="row justify-content-center">
            <div class="col-md-3 col-9">
                <a href="{% url 'board:write_message' %}" class="btn btn-primary btn-block">我要留言</a>
            </div>
        </div>
        <br>

        <div class="text-center">
            {% if last_page == current_page %}
                <a class="btn btn-primary disabled" href="{% url 'board:index' last_page %}">上一页</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'board:index' last_page %}">上一页</a>
            {% endif %}
            <span> 第{{ current_page }} / {{ total_pages }}页 </span>
            {% if next_page == current_page %}
                <a class="btn btn-primary disabled" href="{% url 'board:index' next_page %}">下一页</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'board:index' next_page %}">下一页</a>
            {% endif %}
        </div>

    </div>

{% endblock %}

board/templates/board/login.html
{% extends "board/base.html" %}
{% load static %}

{% block mainbody %}

    <div class="text-center" style="margin-top: 50px;">
        <div class="jumbotron">
            <form action="{% url 'board:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username-box">用户名</label>
                    <input name="username" type="text" class="form-control" id="username-box">
                </div>
                <div class="form-group">
                    <label for="password-box">密码</label>
                    <input name="password" type="password" class="form-control" id="password-box">
                </div>
                <div class="row justify-content-center">
                    <div class="col-6">
                        <input class="btn btn-primary btn-block" type="submit" value="登陆">
                    </div>
                </div>
            </form>
            <div class="row justify-content-center">
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'board:index' %}">返回</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

board/templates/board/manage.html
{% extends "board/base.html" %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand navbar-dark bg-light">
    <a class="navbar-brand" href="">
        <img src="{% static 'board/assets/top.png' %}" alt="Logo">
    </a>
    <div class="navbar-text text-dark text-center lead" style="margin: 0 auto;font-size: 30px;font-weight: bold;">留言板
    </div>

    <ul class="navbar-nav navbar-right">
        <li class="nav-item">
            <a class="nav-link text-info lead text-center" style="width: 85px;" href="{% url 'board:logout' %}">注销</a>
        </li>
    </ul>
</nav>
{% endblock %}

{% block mainbody %}
    <div class="text-center" style="margin-top: 50px; margin-bottom: 50px;">
        {% if need_to_check_list %}
            <table class="table table-hover">
                <thead>
                <tr>
                    <th width="10%" scope="col">留言人</th>
                    <th width="15%" scope="col">留言时间</th>
                    <th width="45%" scope="col">内容</th>
                    <th width="15%" scope="col">状态</th>
                    <th width="15%" scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for message in need_to_check_list %}
                    <tr>
                        <td>{{ message.wechat_id }}</td>
                        <td>{{ message.send_time|date:"Y年n月j日" }}</td>
                        <td>{{ message.message_text }}</td>
                        <td>
                            {% if message.is_checked %}
                                已通过
                                {% if message.response_text %}
                                    (已回复)
                                {% endif %}
                            {% else %}
                                未审核
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'board:check_pass' message_id=message.id page_num=current_page %}">通过</a>
                            <a href="{% url 'board:detail' message_id=message.id page_num=current_page %}">回复</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No message are available.</p>
        {% endif %}
        <br>
        <div class="text-center">
            {% if last_page == current_page %}
                <a class="btn btn-primary disabled" href="{% url 'board:manage' last_page %}">上一页</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'board:manage' last_page %}">上一页</a>
            {% endif %}
            <span> 第{{ current_page }} / {{ total_pages }}页 </span>
            {% if next_page == current_page %}
                <a class="btn btn-primary disabled" href="{% url 'board:manage' next_page %}">下一页</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'board:manage' next_page %}">下一页</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

board/templates/board/write_message.html
{% extends "board/base.html" %}
{% load static %}

{% block mainbody %}
    <div class="text-center" style="margin-top: 50px;">
        <div class="jumbotron">
            <form action="{% url 'board:write_message' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="wechat-box">昵称</label>
                    <input required name="wechat-box" type="text" class="form-control" id="wechat-box">
                </div>
                <div class="form-group">
                    <label for="text-box">留言内容</label>
                    <textarea required name="text-box" class="form-control" id="text-box" rows="3"></textarea>
                </div>
                <div class="row justify-content-center">
                    <div class="col-6">
                        <input class="btn btn-primary btn-block" type="submit" value="提交">
                    </div>
                </div>
            </form>
            <div class="row justify-content-center">
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'board:index' %}">返回</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}